---
name: 'Version Increment'
description: Inspects the git tags to determine the current normal version, and returns the next version number

branding:
  icon: plus
  color: purple

inputs:
  scheme:
    description: 'Versioning scheme - semver, or, calver (defaults to semver)'
    required: false
    default: 'semver'
  pep440:
    description: 'PEP440 compatibility mode - shifts the pre-release version information into build metadata instead'
    required: false
    default: false
  increment:
    description: |
      Field to increment - major, minor, or, patch (defaults to patch)

      Not applicable to `calver` scheme
    required: false
    default: 'patch'
  release_branch:
    description: "Specify a non-main branch to use for the release tag (the one without -prerelease). If empty, will use the default branch for the repo."
    required:
    type: string

outputs:
  current-version:
    description: 'Current normal version detected'
    value: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
  current-v-version:
    description: 'Current normal version detected, prefixed with a `v` charatcter'
    value: ${{ steps.version-lookup.outputs.CURRENT_V_VERSION }}
  version:
    description: 'Incremented version calculated'
    value: ${{ steps.version-increment.outputs.VERSION }}
  v-version:
    description: 'Incremented version calculated, prefixed with a `v` charatcter'
    value: ${{ steps.version-increment.outputs.V_VERSION }}  
  major-version:
    description: 'Major number of the incremented version'
    value: ${{ steps.version-increment.outputs.MAJOR_VERSION }}
  minor-version:
    description: 'Minor number of the incremented version'
    value: ${{ steps.version-increment.outputs.MINOR_VERSION }}
  patch-version:
    description: 'Patch number of the incremented version'
    value: ${{ steps.version-increment.outputs.PATCH_VERSION }}
  pre-release-label:
    description: 'Pre-release label of the incremented version'
    value: ${{ steps.version-increment.outputs.PRE_RELEASE_LABEL }}
  major-v-version:
    description: 'Major number of the incremented version, prefixed with a `v` charatcter'
    value: ${{ steps.version-increment.outputs.MAJOR_V_VERSION }}
  minor-v-version:
    description: 'Minor number of the incremented version, prefixed with a `v` charatcter'
    value: ${{ steps.version-increment.outputs.MINOR_V_VERSION }}
  patch-v-version:
    description: 'Patch number of the incremented version, prefixed with a `v` charatcter'
    value: ${{ steps.version-increment.outputs.PATCH_V_VERSION }}

runs:
  using: "composite"
  steps:
    - id: version-lookup
      run: ${{ github.action_path }}/version-lookup.sh
      shell: bash
      env:
        scheme: ${{ inputs.scheme }}

    - id: version-increment
      run: ${{ github.action_path }}/version-increment.sh
      shell: bash
      env:
        current_version: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
        increment: ${{ inputs.increment }}
        pep440: ${{ inputs.pep440 }}
        scheme: ${{ inputs.scheme }}
        release_branch: ${{ inputs.release_branch }}
